name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  lint_and_test:
    name: Lint & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
        name: Npm install
      - run: npm run lint
        name: Lint source code
      - run: npm test
        name: Test source code